name: 'IIS Service Action'

description: 'A GitHub action that can start, stop, or restart an On-Prem IIS server.'

inputs:
  server:
    description: 'The name of the target server'
    required: true
  service-account-id:
    description: 'The service account name'
    required: true
  service-account-password:
    description: 'The service account password'
    required: true
  web-site-name:
    description: 'The name of the web site'
    default: ''
    required: false
  web-site-path:
    description: 'The local directory of the web site, i.e., "c:\inetpub\webapp"'
    default: ''
    required: false
  app-pool-name:
    description: 'IIS app pool name'
    required: true
  action:
    description: 'Specify start, stop, restart, create-site, or create-app-pool as the action to perform'
    default: 'start'
    required: true
  server-public-key:
    description: 'Path to remote server public ssl key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Action
      id: action
      shell: powershell
      run: |
        $secure_password = ConvertTo-SecureString -String ${{ inputs.service-account-password }} -AsPlainText -Force
        ${{ github.action_path }}/iis_action.ps1 `
          -server ${{ inputs.server }} `
          -web_site_name '${{ inputs.web-site-name }}' `
          -web_site_path '${{ inputs.web-site-path }}' `
          -app_pool_name ${{ inputs.app-pool-name }} `
          -user_id ${{ inputs.service-account-id }} `
          -password $secure_password `
          -action ${{ inputs.action }} `
          -cert_path ${{ inputs.server-public-key }}
