name: 'IIS Service Action'

description: 'A GitHub action that can start, stop, or restart an On-Prem IIS app pool or create an IIS site.'

inputs:
  server:
    description: 'The name of the target server'
    required: true
  service-account-id:
    description: 'The service account name'
    required: true
  service-account-password:
    description: 'The service account password'
    required: true
  web-site-name:
    description: 'The name of the web site'
    default: ''
    required: false
  web-site-host-header:
    description: 'The host-header the web site should respond to'
    default: ''
    required: false
  web-site-path:
    description: 'The local directory location of the web site, i.e., "c:\inetpub\webapp"'
    default: ''
    required: false
  web-site-cert-path:
    description: 'The private cert file path for site https binding'
    default: ''
    required: false
  web-site-cert-password:
    description: 'The private cert file password'
    default: ''
    required: false
  app-pool-name:
    description: 'IIS app pool name'
    required: true
  action:
    description: |
      Specify app-pool-start, app-pool-stop, app-pool-restart, app-pool-create, app-pool-status
      or site-create as the action to perform
    default: 'start'
    required: true
  server-public-key:
    description: 'Path to remote server public ssl key'
    required: true

outputs:
  app-pool-status:
    description: |
      If the action app-pool-status is requested, this value will
      be populated with its information.
    value: '${{ steps.action.outputs.app-pool-status }}'

runs:
  using: 'composite'
  steps:
    - name: Action
      id: action
      shell: powershell
      run: |
        $secure_password = ConvertTo-SecureString -String ${{ inputs.service-account-password }} -AsPlainText -Force
        $secure_cert_password = ConvertTo-SecureString -String ${{ inputs.web-site-cert-password }} -AsPlainText -Force
        ${{ github.action_path }}/iis_action.ps1 `
          -action ${{ inputs.action }} `
          -server ${{ inputs.server }} `
          -web_site_name '${{ inputs.web-site-name }}' `
          -web_site_host_header '${{ inputs.web-site-host-header }}' `
          -web_site_path '${{ inputs.web-site-path }}' `
          -web_site_cert_path '${{ inputs.web-site-cert-path }}' `
          -web_site_cert_password $secure_cert_password `
          -app_pool_name ${{ inputs.app-pool-name }} `
          -user_id ${{ inputs.service-account-id }} `
          -password $secure_password `
          -cert_path ${{ inputs.server-public-key }}
