name: Test Action

on: [push]

jobs:
  start-iis:
   runs-on: [self-hosted, windows]
   steps:
    - name: IIS Test
      id: iis-test
      uses: im-open/iis-service-action@v0
      with:
        server: '10.207.164.190'
        service-account-id: ${{secrets.admin_user}}
        service-account-password: ${{secrets.admin_password}}
        app-pool-name: 'action-test-pool'
        action: 'start'