name: Test Action

on: [push]

jobs:
  start-iis:
   runs-on: [self-hosted, windows]
   steps:
    - name: Checkout
      id: Checkout
      uses: actions/checkout@v2
    - name: IIS start
      id: iis-start
      uses: im-open/iis-service-action@iis-action-creation
      with:
        server: '10.207.164.190'
        service-account-id: ${{secrets.admin_user}}
        service-account-password: ${{secrets.admin_password}}
        app-pool-name: 'action-test-pool'
        action: 'start'
        server-public-key: './test-cert'
    - name: IIS restart
      id: iis-restart
      uses: im-open/iis-service-action@iis-action-creation
      with:
        server: '10.207.164.190'
        service-account-id: ${{secrets.admin_user}}
        service-account-password: ${{secrets.admin_password}}
        app-pool-name: 'action-test-pool'
        action: 'restart'
        server-public-key: './test-cert'
    - name: IIS stop
      id: iis-stop
      uses: im-open/iis-service-action@iis-action-creation
      with:
        server: '10.207.164.190'
        service-account-id: ${{secrets.admin_user}}
        service-account-password: ${{secrets.admin_password}}
        app-pool-name: 'action-test-pool'
        action: 'stop'
        server-public-key: './test-cert'

